# Generated by Django 4.2.8 on 2026-01-26 08:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("newsapi", "NewsAPI"),
                            ("tavily", "Tavily"),
                            ("user", "User Generated"),
                        ],
                        default="newsapi",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai_ml", "AI/ML"),
                            ("blockchain", "Blockchain"),
                            ("web_dev", "Web Development"),
                            ("app_dev", "App Development"),
                            ("cybersecurity", "Cybersecurity"),
                            ("cloud", "Cloud Computing"),
                            ("general", "General Tech"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("is_approved", models.BooleanField(default=True)),
                ("views", models.IntegerField(default=0)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "h_index",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "credentials",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("experience", models.TextField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.FileField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("is_author", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categories", models.JSONField(default=list)),
                ("notification_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Preferences",
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="api.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "article")},
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-published_at"], name="api_article_publish_0044e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category"], name="api_article_categor_d8241f_idx"
            ),
        ),
    ]
