[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = --maxfail=1 -q --cov=./backend --cov-report=term-missing

# include root tests folder
norecursedirs = .git venv env
