# Generated by Django 4.2.7 on 2026-01-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_type', models.CharField(choices=[('tavily', 'Tavily'), ('newsapi', 'NewsAPI')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('last_fetch', models.DateTimeField(blank=True, null=True)),
                ('fetch_interval', models.IntegerField(default=60, help_text='Minutes between fetches')),
            ],
            options={
                'db_table': 'news_sources',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('articles_fetched', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='news.newssource')),
            ],
            options={
                'db_table': 'fetch_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
